.PHONY: clean All

All:
	@echo "----------Building project:[ Astar_search - Debug ]----------"
	@cd "Astar_search" && "$(MAKE)" -f  "Astar_search.mk"
clean:
	@echo "----------Cleaning project:[ Astar_search - Debug ]----------"
	@cd "Astar_search" && "$(MAKE)" -f  "Astar_search.mk" clean
